# Generated by Django 4.2.10 on 2024-02-17 06:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('suspects', models.JSONField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=256, null=True)),
                ('video_recording', models.FileField(blank=True, upload_to='cases/videos_recs')),
                ('supporting_docs', models.FileField(blank=True, null=True, upload_to='cases/supporting_docs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=100)),
                ('cause', models.CharField(max_length=100)),
                ('case', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sections', to='api.case')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('precautions', models.CharField(max_length=256)),
                ('procedure', models.CharField(max_length=256)),
                ('case', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='evidences', to='api.case')),
            ],
        ),
    ]
