# Generated by Django 4.2.10 on 2024-02-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='precaution_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='section_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
