# Generated by Django 4.2.10 on 2024-02-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_case_precaution_list_case_section_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='procedure_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
