# Generated by Django 4.2.10 on 2024-02-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_case_procedure_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='objects_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
