# Generated by Django 4.2.10 on 2024-02-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_case_objects_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='precaution_list',
            new_name='evdience_detail_list',
        ),
        migrations.RemoveField(
            model_name='case',
            name='procedure_list',
        ),
    ]
