# Generated by Django 4.2.10 on 2024-02-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_precaution_list_case_evdience_detail_list_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='evdience_detail_list',
            new_name='evidence_detail_list',
        ),
    ]
